import { Injectable } from "@angular/core";
import { fadeInItems } from "@angular/material/menu";
import dayjs from "dayjs";
import * as pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "../../../../assets/vfs_fonts";
import { setAllCustomerArrearStyle , misAllMinistryCenterwiseSummaryDefaultStyle, misAllMinistryCenterwiseSummaryPageMargin, misMinistrySummaryHeaderMargin, misMinistrySummaryStyle, setHeading, setPdfMakeFonts, setPoultryStyles, setSubHeading, setSubSetHeading, setNewConnectionStyle, setMosqueAndOtherPlacesStyles, setCommonStyle } from "../config/pdfMakeConfig";
import { MiscUntracedCustModel, UntracedCustModel } from "../../../model/get-untraced-cust.model";
(<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;

@Injectable({
  providedIn: 'root'
})
export class UntracePenaltySupplimentaryReportService {
  defaultColur = "#0c0d0d"

  constructor() { }

  generatePdf(data: any, reportObject: any) {
    //@ts-ignore
    pdfMake.fonts = setPdfMakeFonts;
    //@ts-ignore
    const documentDefinition = this.getDocumentDefinition(data, reportObject);
    //@ts-ignore
    return pdfMake.createPdf(documentDefinition);
  }

  
  private getDocumentDefinition(data: any, reportObject: any) {
    return {
      info: {
        title: "Untrace Penalty Supplimentary",
        author: "BPDB",
        subject: "Untrace Penalty Supplimentary",
        keywords: "keywords for document",
      },
      pageSize: 'A4',
      pageOrientation: 'landscape',    
      footer: (currentPage, PageCount)=> {
        return {
          table: {
            widths: ['*', '*'],
            body: [
              [
                { text: `পৃষ্ঠা ${this.translateNumber(currentPage, 2)} এর ${this.translateNumber(PageCount, 2)}`, style: ['setFooterLeft'], margin: [30, 5, 30, 0] }, 
                { text: this.translateNumber(dayjs(new Date()).format('DD/MM/YYYY'), 2), style: ['setFooterRight'], margin: [30, 5, 30, 0] }
              ],
            ]
          },
          layout: 'noBorders'
        }
      },
      heder:this.getHeading(data,reportObject),
      content: [ 
        this.UntraceCustomerReceiptArrearInfo(data),
        this.UntraceCustomerPenaltyReceiptInfo(data),
        this.UntraceSupplementaryBillingInformation(data),
      ],
      
      pageMargins: [30, 20, 30, 30],
      defaultStyle: {
        font: 'bangla',
        alignment: 'center',
        fontSize: 7.4,
        color: '#111',
      },
      styles: setAllCustomerArrearStyle,

    };
  }

  private translateNumber(num, option = 1) {
    let banglaDigits = ["০", "১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯"]
    if (option == 1) {
      num = Number(num).toLocaleString(undefined, { minimumFractionDigits: 2 })
    }
    return num.toString().replace(/\d/g, x => banglaDigits[x]);
  }

  private getHeading(data: any, reportObj: any){
    // const totalCount = data.length;
    const phase = {
      margin: misMinistrySummaryHeaderMargin,
      table: {
        dontBreakRows: true,
        widths: [70, 'auto', 40, '*', 40, 45, 45, 'auto', 'auto', 40],
        margin: [0, 0, 0, 0],
        body: [
          [
            {
              image: `logo.png`,
              width: 70,
              height: 60,
              color: 'gray',
              rowSpan: 5,
              colSpan: 2,
              alignment: 'right',
              margin: [-145, -2, 0, 0],
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
          ],
          [
            {},
            {},
            {
              text: 'BANGLADESH POWER DEVELOPMENT BOARD',
              style: [setNewConnectionStyle.setTitleBold],
              colSpan: 5,
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
          ],
          [
            {},
            {},
            {
              // text: `Untraceable Customer List`,
              // style: [setSubSetHeading],
              // colSpan: 5,
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
          ],
          [
            {},
            {},
            {
              // text: `Report Processing Month`,
              // style: [setSubSetHeading],
              // colSpan: 4,
            },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
          ],
          [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
          ],
        ],
      },
      layout: 'noBorders',
    };
    // return phase;
  }
  private UntraceCustomerReceiptArrearInfo(data:any){
    const phase = {
      margin: [0, 0, 0, 0],
      table: {
        dontBreakRows: true,
        headerRows: 4,
        widths: [35, "*",65,65,65,65,65,65,65,65,65 ],
        body: [
          [
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `নিখোঁজ গ্রাহকের বকেয়া আদায়ের তথ্য, মে/২৩`,
              style: [setMosqueAndOtherPlacesStyles.fontSize,],
              border: [false, false, false, false],
              colSpan: 4,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `ক্রমিক নং`,
              style: [],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `অঞ্চলের নাম`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে এপ্রিল'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মে'২৩ মাস`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে মে'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সনাক্তকৃত গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `বকেয়ার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সনাক্তকৃত গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `বকেয়ার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সনাক্তকৃত গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `বকেয়ার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `১`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `২`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৩`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৪`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৫`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৯=৩+৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১০=৪+৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১১=৫+৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
        ],
      },
    };
    // Total 
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: `মোট`,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    // Empty Row     
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [false, false, false, false],
          colSpan: 11,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    return phase;
  }

  private UntraceCustomerPenaltyReceiptInfo(data:any){
    const phase = {
      margin: [0, 0, 0, 0],
      table: {
        dontBreakRows: true,
        headerRows: 4,
        widths: [35, "*",65,65,65,65,65,65,65,65,65 ],
        body: [
          [
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: [],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `অবৈধ গ্রাহকের জরিমানা আদায়ের তথ্য, মে/২৩`,
              style: [setMosqueAndOtherPlacesStyles.fontSize,],
              border: [false, false, false, false],
              colSpan: 6,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `ক্রমিক নং`,
              style: [],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `অঞ্চলের নাম`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে এপ্রিল'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মে'২৩ মাস`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে মে'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `অবৈধ গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `জরিমানার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `অবৈধ গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `জরিমানার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `অবৈধ গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `জরিমানার পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `১`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `২`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৩`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৪`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৫`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৯=৩+৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১০=৪+৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১১=৫+৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
        ],
      },
    };
    // Total 
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: `মোট`,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    
    // Empty Row     
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [false, false, false, false],
          colSpan: 11,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    return phase;
  }

  private UntraceSupplementaryBillingInformation(data:any){
    const phase = {
      margin: [0, 0, 0, 0],
      table: {
        dontBreakRows: true,
        headerRows: 4,
        widths: [35, "*",65,65,65,65,65,65,65,65,65 ],
        body: [
          [
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: [],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিল আদায়ের তথ্য, মে/২৩`,
              style: [setMosqueAndOtherPlacesStyles.fontSize,],
              border: [false, false, false, false],
              colSpan: 5,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: [],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [false, false, false, false],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `ক্রমিক নং`,
              style: [],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `অঞ্চলের নাম`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:2,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে এপ্রিল'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মে'২৩ মাস`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `মার্চ'২১ হতে মে'২৩ মাস পর্যন্ত`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 3,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: ``,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিল প্রদানকারী গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিলের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিল প্রদানকারী গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিলের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },{
              text: `সম্পূরক বিল প্রদানকারী গ্রাহক সংখ্যা`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `সম্পূরক বিলের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `আদায়ের পরিমান(টাকা)`,
              style: [setCommonStyle.setBanglaHeadingFont,],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
          [
            {
              text: `১`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `২`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৩`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৪`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৫`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `৯=৩+৬`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১০=৪+৭`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
            {
              text: `১১=৫+৮`,
              style: ["setBold",],
              border: [true, true, true, true],
              colSpan: 1,
              rowSpan:1,
              alignment: "center",
            },
          ],
        ],
      },
    };
    // Total 
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: `মোট`,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    
    // Empty Row     
    phase.table.body.push(
      [
        {
          text: ``,
          style: ["setBold",],
          border: [false, false, false, false],
          colSpan: 11,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
        {
          text: ``,
          style: ["setBold",],
          border: [true, true, true, true],
          colSpan: 1,
          rowSpan:1,
          alignment: "center",
        },
      ]
    )
    return phase;
  }
  private setTableBorder() {
    const d = this.defaultColur;
    return {
      hLineWidth: function (i, node) {
        return i === 0 || i === node.table.body.length ? 1 : 1;
      },
      vLineWidth: function (i, node) {
        return i === 0 || i === node.table.widths.length ? 1 : 1;
      },
      hLineColor: function (i, node) {
        return i === 0 || i === node.table.body.length ? d : d;
      },
      vLineColor: function (i, node) {
        return i === 0 || i === node.table.widths.length ? d : d;
      },
      paddingBottom: function (i, node) {
        return 5;
      },
    };
  }
}
